name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: '11.5'

      - name: NPM CI with cache
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build
      
